// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
	"internal"
)

var _ = internal.GetEnvOrDefault

// Runpod API Token
func GetToken(ctx *pulumi.Context) string {
	return config.Get(ctx, "runpod:token")
}
