// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace RunpodInfra.Runpod
{
    [RunpodResourceType("runpod:index:Endpoint")]
    public partial class Endpoint : global::Pulumi.CustomResource
    {
        [Output("endpoint")]
        public Output<Outputs.Endpoint> Endpoint { get; private set; } = null!;

        [Output("gpuIds")]
        public Output<string> GpuIds { get; private set; } = null!;

        [Output("idleTimeout")]
        public Output<int?> IdleTimeout { get; private set; } = null!;

        [Output("locations")]
        public Output<string?> Locations { get; private set; } = null!;

        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        [Output("networkVolumeId")]
        public Output<string?> NetworkVolumeId { get; private set; } = null!;

        [Output("scalerType")]
        public Output<string?> ScalerType { get; private set; } = null!;

        [Output("scalerValue")]
        public Output<int?> ScalerValue { get; private set; } = null!;

        [Output("templateId")]
        public Output<string?> TemplateId { get; private set; } = null!;

        [Output("workersMax")]
        public Output<int?> WorkersMax { get; private set; } = null!;

        [Output("workersMin")]
        public Output<int?> WorkersMin { get; private set; } = null!;


        /// <summary>
        /// Create a Endpoint resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Endpoint(string name, EndpointArgs args, CustomResourceOptions? options = null)
            : base("runpod:index:Endpoint", name, args ?? new EndpointArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Endpoint(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("runpod:index:Endpoint", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/runpod/pulumi-runpod-native",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Endpoint resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Endpoint Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new Endpoint(name, id, options);
        }
    }

    public sealed class EndpointArgs : global::Pulumi.ResourceArgs
    {
        [Input("gpuIds", required: true)]
        public Input<string> GpuIds { get; set; } = null!;

        [Input("idleTimeout")]
        public Input<int>? IdleTimeout { get; set; }

        [Input("locations")]
        public Input<string>? Locations { get; set; }

        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        [Input("networkVolumeId")]
        public Input<string>? NetworkVolumeId { get; set; }

        [Input("scalerType")]
        public Input<string>? ScalerType { get; set; }

        [Input("scalerValue")]
        public Input<int>? ScalerValue { get; set; }

        [Input("templateId")]
        public Input<string>? TemplateId { get; set; }

        [Input("workersMax")]
        public Input<int>? WorkersMax { get; set; }

        [Input("workersMin")]
        public Input<int>? WorkersMin { get; set; }

        public EndpointArgs()
        {
        }
        public static new EndpointArgs Empty => new EndpointArgs();
    }
}
