// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace RunpodInfra.Runpod
{
    [RunpodResourceType("runpod:index:NetworkStorage")]
    public partial class NetworkStorage : global::Pulumi.CustomResource
    {
        [Output("dataCenterId")]
        public Output<string> DataCenterId { get; private set; } = null!;

        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        [Output("networkStorage")]
        public Output<Outputs.NetworkStorage> NetworkStorage { get; private set; } = null!;

        [Output("size")]
        public Output<int> Size { get; private set; } = null!;


        /// <summary>
        /// Create a NetworkStorage resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public NetworkStorage(string name, NetworkStorageArgs args, CustomResourceOptions? options = null)
            : base("runpod:index:NetworkStorage", name, args ?? new NetworkStorageArgs(), MakeResourceOptions(options, ""))
        {
        }

        private NetworkStorage(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("runpod:index:NetworkStorage", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/runpod/pulumi-runpod-native",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing NetworkStorage resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static NetworkStorage Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new NetworkStorage(name, id, options);
        }
    }

    public sealed class NetworkStorageArgs : global::Pulumi.ResourceArgs
    {
        [Input("dataCenterId", required: true)]
        public Input<string> DataCenterId { get; set; } = null!;

        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        [Input("size", required: true)]
        public Input<int> Size { get; set; } = null!;

        public NetworkStorageArgs()
        {
        }
        public static new NetworkStorageArgs Empty => new NetworkStorageArgs();
    }
}
