// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace RunpodInfra.Runpod
{
    [RunpodResourceType("runpod:index:Template")]
    public partial class Template : global::Pulumi.CustomResource
    {
        [Output("containerDiskInGb")]
        public Output<int> ContainerDiskInGb { get; private set; } = null!;

        [Output("containerRegistryAuthId")]
        public Output<string?> ContainerRegistryAuthId { get; private set; } = null!;

        [Output("dockerArgs")]
        public Output<string> DockerArgs { get; private set; } = null!;

        [Output("env")]
        public Output<ImmutableArray<Outputs.PodEnv>> Env { get; private set; } = null!;

        [Output("imageName")]
        public Output<string> ImageName { get; private set; } = null!;

        [Output("isPublic")]
        public Output<bool?> IsPublic { get; private set; } = null!;

        [Output("isServerless")]
        public Output<bool?> IsServerless { get; private set; } = null!;

        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        [Output("ports")]
        public Output<string?> Ports { get; private set; } = null!;

        [Output("readme")]
        public Output<string?> Readme { get; private set; } = null!;

        [Output("startJupyter")]
        public Output<bool?> StartJupyter { get; private set; } = null!;

        [Output("startSsh")]
        public Output<bool?> StartSsh { get; private set; } = null!;

        [Output("template")]
        public Output<Outputs.Template> Template { get; private set; } = null!;

        [Output("volumeInGb")]
        public Output<int> VolumeInGb { get; private set; } = null!;

        [Output("volumeMountPath")]
        public Output<string?> VolumeMountPath { get; private set; } = null!;


        /// <summary>
        /// Create a Template resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Template(string name, TemplateArgs args, CustomResourceOptions? options = null)
            : base("runpod:index:Template", name, args ?? new TemplateArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Template(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("runpod:index:Template", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/runpod/pulumi-runpod-native",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Template resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Template Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new Template(name, id, options);
        }
    }

    public sealed class TemplateArgs : global::Pulumi.ResourceArgs
    {
        [Input("containerDiskInGb", required: true)]
        public Input<int> ContainerDiskInGb { get; set; } = null!;

        [Input("containerRegistryAuthId")]
        public Input<string>? ContainerRegistryAuthId { get; set; }

        [Input("dockerArgs", required: true)]
        public Input<string> DockerArgs { get; set; } = null!;

        [Input("env", required: true)]
        private InputList<Inputs.PodEnvArgs>? _env;
        public InputList<Inputs.PodEnvArgs> Env
        {
            get => _env ?? (_env = new InputList<Inputs.PodEnvArgs>());
            set => _env = value;
        }

        [Input("imageName", required: true)]
        public Input<string> ImageName { get; set; } = null!;

        [Input("isPublic")]
        public Input<bool>? IsPublic { get; set; }

        [Input("isServerless")]
        public Input<bool>? IsServerless { get; set; }

        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        [Input("ports")]
        public Input<string>? Ports { get; set; }

        [Input("readme")]
        public Input<string>? Readme { get; set; }

        [Input("startJupyter")]
        public Input<bool>? StartJupyter { get; set; }

        [Input("startSsh")]
        public Input<bool>? StartSsh { get; set; }

        [Input("volumeInGb", required: true)]
        public Input<int> VolumeInGb { get; set; } = null!;

        [Input("volumeMountPath")]
        public Input<string>? VolumeMountPath { get; set; }

        public TemplateArgs()
        {
        }
        public static new TemplateArgs Empty => new TemplateArgs();
    }
}
