// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace RunpodInfra.Runpod.Outputs
{

    [OutputType]
    public sealed class DataCenter
    {
        public readonly string Id;
        public readonly string Location;
        public readonly string Name;
        public readonly bool StorageSupport;

        [OutputConstructor]
        private DataCenter(
            string id,

            string location,

            string name,

            bool storageSupport)
        {
            Id = id;
            Location = location;
            Name = name;
            StorageSupport = storageSupport;
        }
    }
}
