// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace RunpodInfra.Runpod.Outputs
{

    [OutputType]
    public sealed class Endpoint
    {
        public readonly string GpuIds;
        public readonly string Id;
        public readonly int IdleTimeout;
        public readonly string Locations;
        public readonly string Name;
        public readonly string NetworkVolumeId;
        public readonly string ScalerType;
        public readonly int ScalerValue;
        public readonly string TemplateId;
        public readonly int WorkersMax;
        public readonly int WorkersMin;

        [OutputConstructor]
        private Endpoint(
            string gpuIds,

            string id,

            int idleTimeout,

            string locations,

            string name,

            string networkVolumeId,

            string scalerType,

            int scalerValue,

            string templateId,

            int workersMax,

            int workersMin)
        {
            GpuIds = gpuIds;
            Id = id;
            IdleTimeout = idleTimeout;
            Locations = locations;
            Name = name;
            NetworkVolumeId = networkVolumeId;
            ScalerType = scalerType;
            ScalerValue = scalerValue;
            TemplateId = templateId;
            WorkersMax = workersMax;
            WorkersMin = workersMin;
        }
    }
}
