// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace RunpodInfra.Runpod.Outputs
{

    [OutputType]
    public sealed class NetworkStorage
    {
        public readonly Outputs.DataCenter DataCenter;
        public readonly string DataCenterId;
        public readonly string Id;
        public readonly string Name;
        public readonly int Size;

        [OutputConstructor]
        private NetworkStorage(
            Outputs.DataCenter dataCenter,

            string dataCenterId,

            string id,

            string name,

            int size)
        {
            DataCenter = dataCenter;
            DataCenterId = dataCenterId;
            Id = id;
            Name = name;
            Size = size;
        }
    }
}
