// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace RunpodInfra.Runpod.Outputs
{

    [OutputType]
    public sealed class PodEnv
    {
        public readonly string Key;
        public readonly string Value;

        [OutputConstructor]
        private PodEnv(
            string key,

            string value)
        {
            Key = key;
            Value = value;
        }
    }
}
