// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace RunpodInfra.Runpod.Outputs
{

    [OutputType]
    public sealed class PodRegistry
    {
        public readonly string Auth;
        public readonly string Pass;
        public readonly string Url;
        public readonly string User;
        public readonly string Username;

        [OutputConstructor]
        private PodRegistry(
            string auth,

            string pass,

            string url,

            string user,

            string username)
        {
            Auth = auth;
            Pass = pass;
            Url = url;
            User = user;
            Username = username;
        }
    }
}
