// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace RunpodInfra.Runpod.Outputs
{

    [OutputType]
    public sealed class SavingsPlanInput
    {
        public readonly string PlanLength;
        public readonly double UpfrontCost;

        [OutputConstructor]
        private SavingsPlanInput(
            string planLength,

            double upfrontCost)
        {
            PlanLength = planLength;
            UpfrontCost = upfrontCost;
        }
    }
}
