// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace RunpodInfra.Runpod.Outputs
{

    [OutputType]
    public sealed class Template
    {
        public readonly bool AdvancedStart;
        public readonly string BoundEndpointId;
        public readonly string Category;
        public readonly int ContainerDiskInGb;
        public readonly string ContainerRegistryAuthId;
        public readonly string DockerArgs;
        public readonly double Earned;
        public readonly ImmutableArray<Outputs.PodEnv> Env;
        public readonly string Id;
        public readonly string ImageName;
        public readonly bool IsPublic;
        public readonly bool IsRunpod;
        public readonly bool IsServerless;
        public readonly string Name;
        public readonly string Ports;
        public readonly string Readme;
        public readonly int RuntimeInMin;
        public readonly bool StartJupyter;
        public readonly string StartScript;
        public readonly bool StartSsh;
        public readonly int VolumeInGb;
        public readonly string VolumeMountPath;

        [OutputConstructor]
        private Template(
            bool advancedStart,

            string boundEndpointId,

            string category,

            int containerDiskInGb,

            string containerRegistryAuthId,

            string dockerArgs,

            double earned,

            ImmutableArray<Outputs.PodEnv> env,

            string id,

            string imageName,

            bool isPublic,

            bool isRunpod,

            bool isServerless,

            string name,

            string ports,

            string readme,

            int runtimeInMin,

            bool startJupyter,

            string startScript,

            bool startSsh,

            int volumeInGb,

            string volumeMountPath)
        {
            AdvancedStart = advancedStart;
            BoundEndpointId = boundEndpointId;
            Category = category;
            ContainerDiskInGb = containerDiskInGb;
            ContainerRegistryAuthId = containerRegistryAuthId;
            DockerArgs = dockerArgs;
            Earned = earned;
            Env = env;
            Id = id;
            ImageName = imageName;
            IsPublic = isPublic;
            IsRunpod = isRunpod;
            IsServerless = isServerless;
            Name = name;
            Ports = ports;
            Readme = readme;
            RuntimeInMin = runtimeInMin;
            StartJupyter = startJupyter;
            StartScript = startScript;
            StartSsh = startSsh;
            VolumeInGb = volumeInGb;
            VolumeMountPath = volumeMountPath;
        }
    }
}
