// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface PodEnvArgs {
    key: pulumi.Input<string>;
    value: pulumi.Input<string>;
}

export interface SavingsPlanInputArgs {
    planLength: pulumi.Input<string>;
    upfrontCost: pulumi.Input<number>;
}

