// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface Endpoint {
    gpuIds: string;
    id: string;
    idleTimeout: number;
    locations: string;
    name: string;
    networkVolumeId: string;
    scalerType: string;
    scalerValue: number;
    templateId: string;
    workersMax: number;
    workersMin: number;
}

export interface PodEnv {
    key: string;
    value: string;
}

export interface Template {
    advancedStart: boolean;
    boundEndpointId: string;
    category: string;
    containerDiskInGb: number;
    containerRegistryAuthId: string;
    dockerArgs: string;
    earned: number;
    env?: outputs.PodEnv[];
    id: string;
    imageName: string;
    isPublic: boolean;
    isRunpod: boolean;
    isServerless: boolean;
    name: string;
    ports: string;
    readme: string;
    runtimeInMin: number;
    startJupyter: boolean;
    startScript: string;
    startSsh: boolean;
    volumeInGb: number;
    volumeMountPath: string;
}

