// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace RunpodInfra.Runpod.Inputs
{

    public sealed class SavingsPlanInputArgs : global::Pulumi.ResourceArgs
    {
        [Input("planLength", required: true)]
        public Input<string> PlanLength { get; set; } = null!;

        [Input("upfrontCost", required: true)]
        public Input<double> UpfrontCost { get; set; } = null!;

        public SavingsPlanInputArgs()
        {
        }
        public static new SavingsPlanInputArgs Empty => new SavingsPlanInputArgs();
    }
}
