# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .endpoint import *
from .network_storage import *
from .pod import *
from .provider import *
from .template import *
from ._inputs import *
from . import outputs

# Make subpackages available:
if typing.TYPE_CHECKING:
    import runpodinfra.config as __config
    config = __config
else:
    config = _utilities.lazy_import('runpodinfra.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "runpod",
  "mod": "index",
  "fqn": "runpodinfra",
  "classes": {
   "runpod:index:Endpoint": "Endpoint",
   "runpod:index:NetworkStorage": "NetworkStorage",
   "runpod:index:Pod": "Pod",
   "runpod:index:Template": "Template"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "runpod",
  "token": "pulumi:providers:runpod",
  "fqn": "runpodinfra",
  "class": "Provider"
 }
]
"""
)
