# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'PodEnvArgs',
    'PodEnvArgsDict',
    'SavingsPlanInputArgs',
    'SavingsPlanInputArgsDict',
]

MYPY = False

if not MYPY:
    class PodEnvArgsDict(TypedDict):
        key: pulumi.Input[_builtins.str]
        value: pulumi.Input[_builtins.str]
elif False:
    PodEnvArgsDict: TypeAlias = Mapping[str, Any]

@pulumi.input_type
class PodEnvArgs:
    def __init__(__self__, *,
                 key: pulumi.Input[_builtins.str],
                 value: pulumi.Input[_builtins.str]):
        pulumi.set(__self__, "key", key)
        pulumi.set(__self__, "value", value)

    @_builtins.property
    @pulumi.getter
    def key(self) -> pulumi.Input[_builtins.str]:
        return pulumi.get(self, "key")

    @key.setter
    def key(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "key", value)

    @_builtins.property
    @pulumi.getter
    def value(self) -> pulumi.Input[_builtins.str]:
        return pulumi.get(self, "value")

    @value.setter
    def value(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "value", value)


if not MYPY:
    class SavingsPlanInputArgsDict(TypedDict):
        plan_length: pulumi.Input[_builtins.str]
        upfront_cost: pulumi.Input[_builtins.float]
elif False:
    SavingsPlanInputArgsDict: TypeAlias = Mapping[str, Any]

@pulumi.input_type
class SavingsPlanInputArgs:
    def __init__(__self__, *,
                 plan_length: pulumi.Input[_builtins.str],
                 upfront_cost: pulumi.Input[_builtins.float]):
        pulumi.set(__self__, "plan_length", plan_length)
        pulumi.set(__self__, "upfront_cost", upfront_cost)

    @_builtins.property
    @pulumi.getter(name="planLength")
    def plan_length(self) -> pulumi.Input[_builtins.str]:
        return pulumi.get(self, "plan_length")

    @plan_length.setter
    def plan_length(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "plan_length", value)

    @_builtins.property
    @pulumi.getter(name="upfrontCost")
    def upfront_cost(self) -> pulumi.Input[_builtins.float]:
        return pulumi.get(self, "upfront_cost")

    @upfront_cost.setter
    def upfront_cost(self, value: pulumi.Input[_builtins.float]):
        pulumi.set(self, "upfront_cost", value)


