# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = [
    'DataCenter',
    'Endpoint',
    'Gpu',
    'NetworkStorage',
    'Pod',
    'PodEnv',
    'PodRegistry',
    'SavingsPlanInput',
    'Template',
]

@pulumi.output_type
class DataCenter(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "storageSupport":
            suggest = "storage_support"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in DataCenter. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        DataCenter.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        DataCenter.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 id: _builtins.str,
                 location: _builtins.str,
                 name: _builtins.str,
                 storage_support: _builtins.bool):
        pulumi.set(__self__, "id", id)
        pulumi.set(__self__, "location", location)
        pulumi.set(__self__, "name", name)
        pulumi.set(__self__, "storage_support", storage_support)

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def location(self) -> _builtins.str:
        return pulumi.get(self, "location")

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="storageSupport")
    def storage_support(self) -> _builtins.bool:
        return pulumi.get(self, "storage_support")


@pulumi.output_type
class Endpoint(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "gpuIds":
            suggest = "gpu_ids"
        elif key == "idleTimeout":
            suggest = "idle_timeout"
        elif key == "networkVolumeId":
            suggest = "network_volume_id"
        elif key == "scalerType":
            suggest = "scaler_type"
        elif key == "scalerValue":
            suggest = "scaler_value"
        elif key == "templateId":
            suggest = "template_id"
        elif key == "workersMax":
            suggest = "workers_max"
        elif key == "workersMin":
            suggest = "workers_min"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in Endpoint. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        Endpoint.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        Endpoint.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 gpu_ids: _builtins.str,
                 id: _builtins.str,
                 idle_timeout: _builtins.int,
                 locations: _builtins.str,
                 name: _builtins.str,
                 network_volume_id: _builtins.str,
                 scaler_type: _builtins.str,
                 scaler_value: _builtins.int,
                 template_id: _builtins.str,
                 workers_max: _builtins.int,
                 workers_min: _builtins.int):
        pulumi.set(__self__, "gpu_ids", gpu_ids)
        pulumi.set(__self__, "id", id)
        pulumi.set(__self__, "idle_timeout", idle_timeout)
        pulumi.set(__self__, "locations", locations)
        pulumi.set(__self__, "name", name)
        pulumi.set(__self__, "network_volume_id", network_volume_id)
        pulumi.set(__self__, "scaler_type", scaler_type)
        pulumi.set(__self__, "scaler_value", scaler_value)
        pulumi.set(__self__, "template_id", template_id)
        pulumi.set(__self__, "workers_max", workers_max)
        pulumi.set(__self__, "workers_min", workers_min)

    @_builtins.property
    @pulumi.getter(name="gpuIds")
    def gpu_ids(self) -> _builtins.str:
        return pulumi.get(self, "gpu_ids")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter(name="idleTimeout")
    def idle_timeout(self) -> _builtins.int:
        return pulumi.get(self, "idle_timeout")

    @_builtins.property
    @pulumi.getter
    def locations(self) -> _builtins.str:
        return pulumi.get(self, "locations")

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="networkVolumeId")
    def network_volume_id(self) -> _builtins.str:
        return pulumi.get(self, "network_volume_id")

    @_builtins.property
    @pulumi.getter(name="scalerType")
    def scaler_type(self) -> _builtins.str:
        return pulumi.get(self, "scaler_type")

    @_builtins.property
    @pulumi.getter(name="scalerValue")
    def scaler_value(self) -> _builtins.int:
        return pulumi.get(self, "scaler_value")

    @_builtins.property
    @pulumi.getter(name="templateId")
    def template_id(self) -> _builtins.str:
        return pulumi.get(self, "template_id")

    @_builtins.property
    @pulumi.getter(name="workersMax")
    def workers_max(self) -> _builtins.int:
        return pulumi.get(self, "workers_max")

    @_builtins.property
    @pulumi.getter(name="workersMin")
    def workers_min(self) -> _builtins.int:
        return pulumi.get(self, "workers_min")


@pulumi.output_type
class Gpu(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "podId":
            suggest = "pod_id"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in Gpu. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        Gpu.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        Gpu.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 id: _builtins.str,
                 pod_id: _builtins.str):
        pulumi.set(__self__, "id", id)
        pulumi.set(__self__, "pod_id", pod_id)

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter(name="podId")
    def pod_id(self) -> _builtins.str:
        return pulumi.get(self, "pod_id")


@pulumi.output_type
class NetworkStorage(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "dataCenter":
            suggest = "data_center"
        elif key == "dataCenterId":
            suggest = "data_center_id"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in NetworkStorage. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        NetworkStorage.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        NetworkStorage.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 data_center: 'outputs.DataCenter',
                 data_center_id: _builtins.str,
                 id: _builtins.str,
                 name: _builtins.str,
                 size: _builtins.int):
        pulumi.set(__self__, "data_center", data_center)
        pulumi.set(__self__, "data_center_id", data_center_id)
        pulumi.set(__self__, "id", id)
        pulumi.set(__self__, "name", name)
        pulumi.set(__self__, "size", size)

    @_builtins.property
    @pulumi.getter(name="dataCenter")
    def data_center(self) -> 'outputs.DataCenter':
        return pulumi.get(self, "data_center")

    @_builtins.property
    @pulumi.getter(name="dataCenterId")
    def data_center_id(self) -> _builtins.str:
        return pulumi.get(self, "data_center_id")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def size(self) -> _builtins.int:
        return pulumi.get(self, "size")


@pulumi.output_type
class Pod(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "adjustedCostPerHr":
            suggest = "adjusted_cost_per_hr"
        elif key == "aiApiId":
            suggest = "ai_api_id"
        elif key == "apiKey":
            suggest = "api_key"
        elif key == "consumerUserId":
            suggest = "consumer_user_id"
        elif key == "containerDiskInGb":
            suggest = "container_disk_in_gb"
        elif key == "containerRegistryAuthId":
            suggest = "container_registry_auth_id"
        elif key == "costMultiplier":
            suggest = "cost_multiplier"
        elif key == "costPerHr":
            suggest = "cost_per_hr"
        elif key == "createdAt":
            suggest = "created_at"
        elif key == "desiredStatus":
            suggest = "desired_status"
        elif key == "dockerArgs":
            suggest = "docker_args"
        elif key == "dockerId":
            suggest = "docker_id"
        elif key == "gpuCount":
            suggest = "gpu_count"
        elif key == "gpuPowerLimitPercent":
            suggest = "gpu_power_limit_percent"
        elif key == "imageName":
            suggest = "image_name"
        elif key == "lastStartedAt":
            suggest = "last_started_at"
        elif key == "lastStatusChange":
            suggest = "last_status_change"
        elif key == "machineId":
            suggest = "machine_id"
        elif key == "memoryInGb":
            suggest = "memory_in_gb"
        elif key == "podType":
            suggest = "pod_type"
        elif key == "templateId":
            suggest = "template_id"
        elif key == "uptimeSeconds":
            suggest = "uptime_seconds"
        elif key == "vcpuCount":
            suggest = "vcpu_count"
        elif key == "volumeEncrypted":
            suggest = "volume_encrypted"
        elif key == "volumeInGb":
            suggest = "volume_in_gb"
        elif key == "volumeKey":
            suggest = "volume_key"
        elif key == "volumeMountPath":
            suggest = "volume_mount_path"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in Pod. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        Pod.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        Pod.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 adjusted_cost_per_hr: _builtins.float,
                 ai_api_id: _builtins.str,
                 api_key: _builtins.str,
                 consumer_user_id: _builtins.str,
                 container_disk_in_gb: _builtins.int,
                 container_registry_auth_id: _builtins.str,
                 cost_multiplier: _builtins.float,
                 cost_per_hr: _builtins.float,
                 created_at: _builtins.str,
                 desired_status: _builtins.str,
                 docker_args: _builtins.str,
                 docker_id: _builtins.str,
                 gpu_count: _builtins.int,
                 gpu_power_limit_percent: _builtins.int,
                 id: _builtins.str,
                 image_name: _builtins.str,
                 last_started_at: _builtins.str,
                 last_status_change: _builtins.str,
                 locked: _builtins.bool,
                 machine_id: _builtins.str,
                 memory_in_gb: _builtins.float,
                 name: _builtins.str,
                 pod_type: _builtins.str,
                 port: _builtins.int,
                 ports: _builtins.str,
                 registry: 'outputs.PodRegistry',
                 template_id: _builtins.str,
                 uptime_seconds: _builtins.int,
                 vcpu_count: _builtins.float,
                 version: _builtins.int,
                 volume_encrypted: _builtins.bool,
                 volume_in_gb: _builtins.float,
                 volume_key: _builtins.str,
                 volume_mount_path: _builtins.str,
                 env: Optional[Sequence[_builtins.str]] = None,
                 gpus: Optional[Sequence['outputs.Gpu']] = None):
        pulumi.set(__self__, "adjusted_cost_per_hr", adjusted_cost_per_hr)
        pulumi.set(__self__, "ai_api_id", ai_api_id)
        pulumi.set(__self__, "api_key", api_key)
        pulumi.set(__self__, "consumer_user_id", consumer_user_id)
        pulumi.set(__self__, "container_disk_in_gb", container_disk_in_gb)
        pulumi.set(__self__, "container_registry_auth_id", container_registry_auth_id)
        pulumi.set(__self__, "cost_multiplier", cost_multiplier)
        pulumi.set(__self__, "cost_per_hr", cost_per_hr)
        pulumi.set(__self__, "created_at", created_at)
        pulumi.set(__self__, "desired_status", desired_status)
        pulumi.set(__self__, "docker_args", docker_args)
        pulumi.set(__self__, "docker_id", docker_id)
        pulumi.set(__self__, "gpu_count", gpu_count)
        pulumi.set(__self__, "gpu_power_limit_percent", gpu_power_limit_percent)
        pulumi.set(__self__, "id", id)
        pulumi.set(__self__, "image_name", image_name)
        pulumi.set(__self__, "last_started_at", last_started_at)
        pulumi.set(__self__, "last_status_change", last_status_change)
        pulumi.set(__self__, "locked", locked)
        pulumi.set(__self__, "machine_id", machine_id)
        pulumi.set(__self__, "memory_in_gb", memory_in_gb)
        pulumi.set(__self__, "name", name)
        pulumi.set(__self__, "pod_type", pod_type)
        pulumi.set(__self__, "port", port)
        pulumi.set(__self__, "ports", ports)
        pulumi.set(__self__, "registry", registry)
        pulumi.set(__self__, "template_id", template_id)
        pulumi.set(__self__, "uptime_seconds", uptime_seconds)
        pulumi.set(__self__, "vcpu_count", vcpu_count)
        pulumi.set(__self__, "version", version)
        pulumi.set(__self__, "volume_encrypted", volume_encrypted)
        pulumi.set(__self__, "volume_in_gb", volume_in_gb)
        pulumi.set(__self__, "volume_key", volume_key)
        pulumi.set(__self__, "volume_mount_path", volume_mount_path)
        if env is not None:
            pulumi.set(__self__, "env", env)
        if gpus is not None:
            pulumi.set(__self__, "gpus", gpus)

    @_builtins.property
    @pulumi.getter(name="adjustedCostPerHr")
    def adjusted_cost_per_hr(self) -> _builtins.float:
        return pulumi.get(self, "adjusted_cost_per_hr")

    @_builtins.property
    @pulumi.getter(name="aiApiId")
    def ai_api_id(self) -> _builtins.str:
        return pulumi.get(self, "ai_api_id")

    @_builtins.property
    @pulumi.getter(name="apiKey")
    def api_key(self) -> _builtins.str:
        return pulumi.get(self, "api_key")

    @_builtins.property
    @pulumi.getter(name="consumerUserId")
    def consumer_user_id(self) -> _builtins.str:
        return pulumi.get(self, "consumer_user_id")

    @_builtins.property
    @pulumi.getter(name="containerDiskInGb")
    def container_disk_in_gb(self) -> _builtins.int:
        return pulumi.get(self, "container_disk_in_gb")

    @_builtins.property
    @pulumi.getter(name="containerRegistryAuthId")
    def container_registry_auth_id(self) -> _builtins.str:
        return pulumi.get(self, "container_registry_auth_id")

    @_builtins.property
    @pulumi.getter(name="costMultiplier")
    def cost_multiplier(self) -> _builtins.float:
        return pulumi.get(self, "cost_multiplier")

    @_builtins.property
    @pulumi.getter(name="costPerHr")
    def cost_per_hr(self) -> _builtins.float:
        return pulumi.get(self, "cost_per_hr")

    @_builtins.property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> _builtins.str:
        return pulumi.get(self, "created_at")

    @_builtins.property
    @pulumi.getter(name="desiredStatus")
    def desired_status(self) -> _builtins.str:
        return pulumi.get(self, "desired_status")

    @_builtins.property
    @pulumi.getter(name="dockerArgs")
    def docker_args(self) -> _builtins.str:
        return pulumi.get(self, "docker_args")

    @_builtins.property
    @pulumi.getter(name="dockerId")
    def docker_id(self) -> _builtins.str:
        return pulumi.get(self, "docker_id")

    @_builtins.property
    @pulumi.getter(name="gpuCount")
    def gpu_count(self) -> _builtins.int:
        return pulumi.get(self, "gpu_count")

    @_builtins.property
    @pulumi.getter(name="gpuPowerLimitPercent")
    def gpu_power_limit_percent(self) -> _builtins.int:
        return pulumi.get(self, "gpu_power_limit_percent")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter(name="imageName")
    def image_name(self) -> _builtins.str:
        return pulumi.get(self, "image_name")

    @_builtins.property
    @pulumi.getter(name="lastStartedAt")
    def last_started_at(self) -> _builtins.str:
        return pulumi.get(self, "last_started_at")

    @_builtins.property
    @pulumi.getter(name="lastStatusChange")
    def last_status_change(self) -> _builtins.str:
        return pulumi.get(self, "last_status_change")

    @_builtins.property
    @pulumi.getter
    def locked(self) -> _builtins.bool:
        return pulumi.get(self, "locked")

    @_builtins.property
    @pulumi.getter(name="machineId")
    def machine_id(self) -> _builtins.str:
        return pulumi.get(self, "machine_id")

    @_builtins.property
    @pulumi.getter(name="memoryInGb")
    def memory_in_gb(self) -> _builtins.float:
        return pulumi.get(self, "memory_in_gb")

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="podType")
    def pod_type(self) -> _builtins.str:
        return pulumi.get(self, "pod_type")

    @_builtins.property
    @pulumi.getter
    def port(self) -> _builtins.int:
        return pulumi.get(self, "port")

    @_builtins.property
    @pulumi.getter
    def ports(self) -> _builtins.str:
        return pulumi.get(self, "ports")

    @_builtins.property
    @pulumi.getter
    def registry(self) -> 'outputs.PodRegistry':
        return pulumi.get(self, "registry")

    @_builtins.property
    @pulumi.getter(name="templateId")
    def template_id(self) -> _builtins.str:
        return pulumi.get(self, "template_id")

    @_builtins.property
    @pulumi.getter(name="uptimeSeconds")
    def uptime_seconds(self) -> _builtins.int:
        return pulumi.get(self, "uptime_seconds")

    @_builtins.property
    @pulumi.getter(name="vcpuCount")
    def vcpu_count(self) -> _builtins.float:
        return pulumi.get(self, "vcpu_count")

    @_builtins.property
    @pulumi.getter
    def version(self) -> _builtins.int:
        return pulumi.get(self, "version")

    @_builtins.property
    @pulumi.getter(name="volumeEncrypted")
    def volume_encrypted(self) -> _builtins.bool:
        return pulumi.get(self, "volume_encrypted")

    @_builtins.property
    @pulumi.getter(name="volumeInGb")
    def volume_in_gb(self) -> _builtins.float:
        return pulumi.get(self, "volume_in_gb")

    @_builtins.property
    @pulumi.getter(name="volumeKey")
    def volume_key(self) -> _builtins.str:
        return pulumi.get(self, "volume_key")

    @_builtins.property
    @pulumi.getter(name="volumeMountPath")
    def volume_mount_path(self) -> _builtins.str:
        return pulumi.get(self, "volume_mount_path")

    @_builtins.property
    @pulumi.getter
    def env(self) -> Optional[Sequence[_builtins.str]]:
        return pulumi.get(self, "env")

    @_builtins.property
    @pulumi.getter
    def gpus(self) -> Optional[Sequence['outputs.Gpu']]:
        return pulumi.get(self, "gpus")


@pulumi.output_type
class PodEnv(dict):
    def __init__(__self__, *,
                 key: _builtins.str,
                 value: _builtins.str):
        pulumi.set(__self__, "key", key)
        pulumi.set(__self__, "value", value)

    @_builtins.property
    @pulumi.getter
    def key(self) -> _builtins.str:
        return pulumi.get(self, "key")

    @_builtins.property
    @pulumi.getter
    def value(self) -> _builtins.str:
        return pulumi.get(self, "value")


@pulumi.output_type
class PodRegistry(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "pass":
            suggest = "pass_"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in PodRegistry. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        PodRegistry.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        PodRegistry.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 auth: _builtins.str,
                 pass_: _builtins.str,
                 url: _builtins.str,
                 user: _builtins.str,
                 username: _builtins.str):
        pulumi.set(__self__, "auth", auth)
        pulumi.set(__self__, "pass_", pass_)
        pulumi.set(__self__, "url", url)
        pulumi.set(__self__, "user", user)
        pulumi.set(__self__, "username", username)

    @_builtins.property
    @pulumi.getter
    def auth(self) -> _builtins.str:
        return pulumi.get(self, "auth")

    @_builtins.property
    @pulumi.getter(name="pass")
    def pass_(self) -> _builtins.str:
        return pulumi.get(self, "pass_")

    @_builtins.property
    @pulumi.getter
    def url(self) -> _builtins.str:
        return pulumi.get(self, "url")

    @_builtins.property
    @pulumi.getter
    def user(self) -> _builtins.str:
        return pulumi.get(self, "user")

    @_builtins.property
    @pulumi.getter
    def username(self) -> _builtins.str:
        return pulumi.get(self, "username")


@pulumi.output_type
class SavingsPlanInput(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "planLength":
            suggest = "plan_length"
        elif key == "upfrontCost":
            suggest = "upfront_cost"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in SavingsPlanInput. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        SavingsPlanInput.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        SavingsPlanInput.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 plan_length: _builtins.str,
                 upfront_cost: _builtins.float):
        pulumi.set(__self__, "plan_length", plan_length)
        pulumi.set(__self__, "upfront_cost", upfront_cost)

    @_builtins.property
    @pulumi.getter(name="planLength")
    def plan_length(self) -> _builtins.str:
        return pulumi.get(self, "plan_length")

    @_builtins.property
    @pulumi.getter(name="upfrontCost")
    def upfront_cost(self) -> _builtins.float:
        return pulumi.get(self, "upfront_cost")


@pulumi.output_type
class Template(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "advancedStart":
            suggest = "advanced_start"
        elif key == "boundEndpointId":
            suggest = "bound_endpoint_id"
        elif key == "containerDiskInGb":
            suggest = "container_disk_in_gb"
        elif key == "containerRegistryAuthId":
            suggest = "container_registry_auth_id"
        elif key == "dockerArgs":
            suggest = "docker_args"
        elif key == "imageName":
            suggest = "image_name"
        elif key == "isPublic":
            suggest = "is_public"
        elif key == "isRunpod":
            suggest = "is_runpod"
        elif key == "isServerless":
            suggest = "is_serverless"
        elif key == "runtimeInMin":
            suggest = "runtime_in_min"
        elif key == "startJupyter":
            suggest = "start_jupyter"
        elif key == "startScript":
            suggest = "start_script"
        elif key == "startSsh":
            suggest = "start_ssh"
        elif key == "volumeInGb":
            suggest = "volume_in_gb"
        elif key == "volumeMountPath":
            suggest = "volume_mount_path"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in Template. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        Template.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        Template.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 advanced_start: _builtins.bool,
                 bound_endpoint_id: _builtins.str,
                 category: _builtins.str,
                 container_disk_in_gb: _builtins.int,
                 container_registry_auth_id: _builtins.str,
                 docker_args: _builtins.str,
                 earned: _builtins.float,
                 id: _builtins.str,
                 image_name: _builtins.str,
                 is_public: _builtins.bool,
                 is_runpod: _builtins.bool,
                 is_serverless: _builtins.bool,
                 name: _builtins.str,
                 ports: _builtins.str,
                 readme: _builtins.str,
                 runtime_in_min: _builtins.int,
                 start_jupyter: _builtins.bool,
                 start_script: _builtins.str,
                 start_ssh: _builtins.bool,
                 volume_in_gb: _builtins.int,
                 volume_mount_path: _builtins.str,
                 env: Optional[Sequence['outputs.PodEnv']] = None):
        pulumi.set(__self__, "advanced_start", advanced_start)
        pulumi.set(__self__, "bound_endpoint_id", bound_endpoint_id)
        pulumi.set(__self__, "category", category)
        pulumi.set(__self__, "container_disk_in_gb", container_disk_in_gb)
        pulumi.set(__self__, "container_registry_auth_id", container_registry_auth_id)
        pulumi.set(__self__, "docker_args", docker_args)
        pulumi.set(__self__, "earned", earned)
        pulumi.set(__self__, "id", id)
        pulumi.set(__self__, "image_name", image_name)
        pulumi.set(__self__, "is_public", is_public)
        pulumi.set(__self__, "is_runpod", is_runpod)
        pulumi.set(__self__, "is_serverless", is_serverless)
        pulumi.set(__self__, "name", name)
        pulumi.set(__self__, "ports", ports)
        pulumi.set(__self__, "readme", readme)
        pulumi.set(__self__, "runtime_in_min", runtime_in_min)
        pulumi.set(__self__, "start_jupyter", start_jupyter)
        pulumi.set(__self__, "start_script", start_script)
        pulumi.set(__self__, "start_ssh", start_ssh)
        pulumi.set(__self__, "volume_in_gb", volume_in_gb)
        pulumi.set(__self__, "volume_mount_path", volume_mount_path)
        if env is not None:
            pulumi.set(__self__, "env", env)

    @_builtins.property
    @pulumi.getter(name="advancedStart")
    def advanced_start(self) -> _builtins.bool:
        return pulumi.get(self, "advanced_start")

    @_builtins.property
    @pulumi.getter(name="boundEndpointId")
    def bound_endpoint_id(self) -> _builtins.str:
        return pulumi.get(self, "bound_endpoint_id")

    @_builtins.property
    @pulumi.getter
    def category(self) -> _builtins.str:
        return pulumi.get(self, "category")

    @_builtins.property
    @pulumi.getter(name="containerDiskInGb")
    def container_disk_in_gb(self) -> _builtins.int:
        return pulumi.get(self, "container_disk_in_gb")

    @_builtins.property
    @pulumi.getter(name="containerRegistryAuthId")
    def container_registry_auth_id(self) -> _builtins.str:
        return pulumi.get(self, "container_registry_auth_id")

    @_builtins.property
    @pulumi.getter(name="dockerArgs")
    def docker_args(self) -> _builtins.str:
        return pulumi.get(self, "docker_args")

    @_builtins.property
    @pulumi.getter
    def earned(self) -> _builtins.float:
        return pulumi.get(self, "earned")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter(name="imageName")
    def image_name(self) -> _builtins.str:
        return pulumi.get(self, "image_name")

    @_builtins.property
    @pulumi.getter(name="isPublic")
    def is_public(self) -> _builtins.bool:
        return pulumi.get(self, "is_public")

    @_builtins.property
    @pulumi.getter(name="isRunpod")
    def is_runpod(self) -> _builtins.bool:
        return pulumi.get(self, "is_runpod")

    @_builtins.property
    @pulumi.getter(name="isServerless")
    def is_serverless(self) -> _builtins.bool:
        return pulumi.get(self, "is_serverless")

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def ports(self) -> _builtins.str:
        return pulumi.get(self, "ports")

    @_builtins.property
    @pulumi.getter
    def readme(self) -> _builtins.str:
        return pulumi.get(self, "readme")

    @_builtins.property
    @pulumi.getter(name="runtimeInMin")
    def runtime_in_min(self) -> _builtins.int:
        return pulumi.get(self, "runtime_in_min")

    @_builtins.property
    @pulumi.getter(name="startJupyter")
    def start_jupyter(self) -> _builtins.bool:
        return pulumi.get(self, "start_jupyter")

    @_builtins.property
    @pulumi.getter(name="startScript")
    def start_script(self) -> _builtins.str:
        return pulumi.get(self, "start_script")

    @_builtins.property
    @pulumi.getter(name="startSsh")
    def start_ssh(self) -> _builtins.bool:
        return pulumi.get(self, "start_ssh")

    @_builtins.property
    @pulumi.getter(name="volumeInGb")
    def volume_in_gb(self) -> _builtins.int:
        return pulumi.get(self, "volume_in_gb")

    @_builtins.property
    @pulumi.getter(name="volumeMountPath")
    def volume_mount_path(self) -> _builtins.str:
        return pulumi.get(self, "volume_mount_path")

    @_builtins.property
    @pulumi.getter
    def env(self) -> Optional[Sequence['outputs.PodEnv']]:
        return pulumi.get(self, "env")


