// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class Endpoint extends pulumi.CustomResource {
    /**
     * Get an existing Endpoint resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Endpoint {
        return new Endpoint(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'runpod:index:Endpoint';

    /**
     * Returns true if the given object is an instance of Endpoint.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Endpoint {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Endpoint.__pulumiType;
    }

    declare public /*out*/ readonly endpoint: pulumi.Output<outputs.Endpoint>;
    declare public readonly gpuIds: pulumi.Output<string>;
    declare public readonly idleTimeout: pulumi.Output<number | undefined>;
    declare public readonly locations: pulumi.Output<string | undefined>;
    declare public readonly name: pulumi.Output<string>;
    declare public readonly networkVolumeId: pulumi.Output<string | undefined>;
    declare public readonly scalerType: pulumi.Output<string | undefined>;
    declare public readonly scalerValue: pulumi.Output<number | undefined>;
    declare public readonly templateId: pulumi.Output<string | undefined>;
    declare public readonly workersMax: pulumi.Output<number | undefined>;
    declare public readonly workersMin: pulumi.Output<number | undefined>;

    /**
     * Create a Endpoint resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: EndpointArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.gpuIds === undefined && !opts.urn) {
                throw new Error("Missing required property 'gpuIds'");
            }
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            resourceInputs["gpuIds"] = args?.gpuIds;
            resourceInputs["idleTimeout"] = args?.idleTimeout;
            resourceInputs["locations"] = args?.locations;
            resourceInputs["name"] = args?.name;
            resourceInputs["networkVolumeId"] = args?.networkVolumeId;
            resourceInputs["scalerType"] = args?.scalerType;
            resourceInputs["scalerValue"] = args?.scalerValue;
            resourceInputs["templateId"] = args?.templateId;
            resourceInputs["workersMax"] = args?.workersMax;
            resourceInputs["workersMin"] = args?.workersMin;
            resourceInputs["endpoint"] = undefined /*out*/;
        } else {
            resourceInputs["endpoint"] = undefined /*out*/;
            resourceInputs["gpuIds"] = undefined /*out*/;
            resourceInputs["idleTimeout"] = undefined /*out*/;
            resourceInputs["locations"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["networkVolumeId"] = undefined /*out*/;
            resourceInputs["scalerType"] = undefined /*out*/;
            resourceInputs["scalerValue"] = undefined /*out*/;
            resourceInputs["templateId"] = undefined /*out*/;
            resourceInputs["workersMax"] = undefined /*out*/;
            resourceInputs["workersMin"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Endpoint.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Endpoint resource.
 */
export interface EndpointArgs {
    gpuIds: pulumi.Input<string>;
    idleTimeout?: pulumi.Input<number>;
    locations?: pulumi.Input<string>;
    name: pulumi.Input<string>;
    networkVolumeId?: pulumi.Input<string>;
    scalerType?: pulumi.Input<string>;
    scalerValue?: pulumi.Input<number>;
    templateId?: pulumi.Input<string>;
    workersMax?: pulumi.Input<number>;
    workersMin?: pulumi.Input<number>;
}
